host: 0.0.0.0
permalink: pretty

title: Miloš Hadžić
description: Hi, I am Miloš Hadžić and this is my blog where I usually write about programming.
twitter_username: miloshadzic

domain: miloshadzic.com

exclude: [vendor]
